apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-aether-config
  labels:
    app: aether-terminal
    release: {{ .Release.Name }}
data:
  aether.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
